UILayer/Controllers/ProductController.cs
using DomainLayer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RepositoryLayer;
using RepositoryLayer.Interface;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UILayer.Datas.Apiservices;
using UILayer.Controllers;
using DomainLayer.Product;
using Microsoft.Extensions.Configuration;
using UILayer.ApiServices;

namespace UILayer.Controllers
{
    public class ProductController : Controller
    {
        IConfiguration _configuration;
        ProductView Storage = null;
        private readonly ProductApi _productApi;
        private IWebHostEnvironment _webHostEnvironment;
        Masterdataapi _masterdataapi;

        public ProductController(IConfiguration configuration, IWebHostEnvironment hostEnvironment)
        {
            _configuration = configuration;
            _productApi = new ProductApi(_configuration);
            _webHostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        
        {
            var products = _productApi.GetProduct();
            return View(products);
        }

        [HttpGet]
        //public IActionResult GetList()

        //{
        //    var products = _productApi.GetProduct();
        //    return new JsonResult(products);
        //}

        [HttpGet]
        //public IActionResult ProductDetails(int id)

        //{
        //    var products = _productApi.GetProduct().Where(x => x.id.Equals(id)).FirstOrDefault();
        //    ViewData["Products"] = products;
        //    return View();
        //}

        public IActionResult Details(int id)
        {
            var products = _productApi.GetById(id);
            return View(products);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            Storage = new ProductView();
            ProductsModel product = _productApi.GetById(id);
            Storage.productName = product.productName;
            Storage.productPrice = product.productPrice;
            Storage.productModel = product.productModel;
            Storage.quantity = product.quantity;
            Storage.description = product.description;
            return View("Create", Storage);
        }

        public ActionResult Delete(int id)
        {
            bool result = _productApi.Delete(id);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductView product)
      {
            if (product.id == 0)
            {
                string stringFileName = UploadFile(product);
                var productsModel = new ProductsModel
                {
                    productName = product.productName,
                    productPrice = product.productPrice,
                    productModel = product.productModel,
                    image = stringFileName,
                    quantity = product.quantity,
                    description = product.description,
                    specification = product.specification                   
                };

                bool result = _productApi.Create(productsModel);
                if (result)
                {
                    return RedirectToAction("Index");                 
                }
              return Content("Failed");
            }
            else
            {
                string stringFileName = UploadFile(product);
                var productsModel = new ProductsModel
                {
                    id = product.id,
                    productName = product.productName,
                    productPrice = product.productPrice,
                    productModel = product.productModel,
                    image = stringFileName,
                    quantity = product.quantity,
                    description = product.description
                };
                bool result = _productApi.Edit(productsModel);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                return Content("Failed");
            }
        }

        private string UploadFile(ProductView product)
        {
            string fileName = null;
            if (product.image != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "Images/ProductImages");
                fileName = Guid.NewGuid().ToString() + "-" + product.image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
        //public IActionResult SearchProduct(string name)
        //{
        //    var data = _productApi.ProductSearch(name);
        //    return View("Index", data);

        //}
        //[HttpPost("filter")]
        //public IActionResult filter(string brandName)
        //{

        //    var data = _productApi.GetProduct().Where(x => x.specification.productBrand.Equals(brandName));

           
        //    //IEnumerable<ProductView> filteredData = (IEnumerable<ProductView>)_productApi.GetProduct().Where(c => c.productStatus.Equals(Status.enable));
        //    //if (filteredData != null)
        //    //{
        //    //    if (brandName != null)
        //    //    {
        //    //        filteredData = (IEnumerable<ProductView>)_productApi.Filter(brandName).Result;
        //    //    }
        //    //    int count = 0;
        //    //    var productCount = filteredData.Count();
        //    //    int cout = 0;
        //    //    for (int i = 0; i <= 0; i++)
        //    //    {
        //    //        if (productCount > 10)
        //    //        {
        //    //            cout += 1;
        //    //        }
        //    //        productCount = productCount - 10;
        //    //    }
        //    //    var result = filteredData.Skip((int)count * 10).Take(10);
        //    //    ViewBag.count = cout;
        //    //    return View("Index", result);
        //    //}

        //    return View("Index");

        }

    }

UILayer/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using UILayer.Datas.Apiservices;
using Microsoft.AspNetCore.Authorization;
using DomainLayer;
using UILayer.ApiServices;
using Microsoft.AspNetCore.Http;
using DomainLayer.EmailService;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.Win32;

namespace UILayer.Controllers
{
    public class UserController : Controller
    {
        private UserApi _userApi;
        private readonly ProductApi _productApi;
        private IConfiguration _configuration;
        private Registration _registration;
        Masterdataapi _Masterdataapi;
        private readonly INotyfService _notyf;
        public UserController(IConfiguration configuration, INotyfService notyf)
        {
            _configuration = configuration;
            _userApi = new UserApi(_configuration);
            _productApi = new ProductApi(_configuration);
            _notyf = notyf;
        }
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            return View(_productApi.GetProduct());
        }

        [HttpGet]
        public IActionResult UserRegister()

        {
            return View();
        }

        [HttpPost]
        public IActionResult UserRegister(Registration registrationView)
        {
            var check = _userApi.UserRegister(registrationView);
            if (check)
            {
                _notyf.Success("Registration Successfully Completed");
            }
            else
            {
                _notyf.Error("Registration Failed, You are already Registered");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Login(string ReturnUrl)
        {
            ViewData["LoginUrl"] = ReturnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Login loginView, string ReturnUrl)
        {
            AdminApi admin = new AdminApi();
            if (ReturnUrl == "/admin")
            {
                if (admin.AdminLogin(loginView))
                {
                    var claims = new List<Claim>();

                    claims.Add(new Claim("password", loginView.password));
                    claims.Add(new Claim("email", loginView.username));
                    claims.Add(new Claim(ClaimTypes.NameIdentifier, loginView.username));
                    claims.Add(new Claim(ClaimTypes.Name, loginView.username));
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                    await HttpContext.SignInAsync(claimsPrincipal);
                    return Redirect("/admin/Index");
                }
            }
            Login userLogin = new Login();
            bool check = _userApi.UserLogin(loginView);
            if (check)
            {
                _registration = _userApi.GetUserInfo().Where(register => register.email == loginView.username && loginView.password.Equals(loginView.password)).FirstOrDefault();
                var claims = new List<Claim>();

                claims.Add(new Claim("password", loginView.password));
                claims.Add(new Claim(ClaimTypes.NameIdentifier, loginView.username));
                claims.Add(new Claim("email", loginView.username));
                claims.Add(new Claim(ClaimTypes.Name, _registration.firstName + " " + _registration.lastName));
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                await HttpContext.SignInAsync(claimsPrincipal);
                return RedirectToAction("Index");
            }
            TempData["Error"] = "*Invalid Email or Password";
            return View("Login");
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("Login");
        }

        [HttpGet]
        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ForgotPassword(ForgotPassword forgotPassword)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    HttpContext.Session.SetString("key", "value");
                    var data = HttpContext.Session.Id;

                    ModelState.Clear();
                    var userDetails = _userApi.GetUserInfo().Where(check => check.email.Equals(forgotPassword.email)).FirstOrDefault();
                    if (userDetails != null)
                    {
                        forgotPassword.emailSent = true;
                        Email email = new Email();
                        email.body = "<a href='https://localhost:44328/user/ResetPassword/" + forgotPassword.email + "/" + data + "'>Click here to reset your password</a>";
                        email.toEmail = forgotPassword.email;
                        email.subject = "reset password";
                        _userApi.Email(email);
                        return View("ForgotPassword", forgotPassword);
                    }
                }
                return View(forgotPassword);
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }

        [HttpGet("/user/ResetPassword/{email}/{sessionId}")]
        public ActionResult ResetPassword(string email, string sessionId)
        {
            if (sessionId == HttpContext.Session.Id)
            {
                var userDetails = _userApi.GetUserInfo().Where(check => check.email.Equals(email)).FirstOrDefault();
                ResetPassword reset = new ResetPassword();
                reset.user = userDetails;
                return View(reset);
            }
            return RedirectToAction("ForgotPassword");
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPassword resetPassword)
        {
            try
            {
                Registration register = new Registration();
                register = _userApi.GetUserInfo().Where(c => c.email.Equals(resetPassword.user.email)).FirstOrDefault();
                register.password = resetPassword.newPassword;
                var result = _userApi.ForgotPassword(register);
                return Redirect("/");
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }
        [HttpPost("filter")]
        public IActionResult filter(string brandName)
        {

            var data = _productApi.GetProduct().Where(x => x.specification.productBrand.Equals(brandName));


            //IEnumerable<ProductView> filteredData = (IEnumerable<ProductView>)_productApi.GetProduct().Where(c => c.productStatus.Equals(Status.enable));
            //if (filteredData != null)
            //{
            //    if (brandName != null)
            //    {
            //        filteredData = (IEnumerable<ProductView>)_productApi.Filter(brandName).Result;
            //    }
            //    int count = 0;
            //    var productCount = filteredData.Count();
            //    int cout = 0;
            //    for (int i = 0; i <= 0; i++)
            //    {
            //        if (productCount > 10)
            //        {
            //            cout += 1;
            //        }
            //        productCount = productCount - 10;
            //    }
            //    var result = filteredData.Skip((int)count * 10).Take(10);
            //    ViewBag.count = cout;
            //    return View("Index", result);
            //}

            return View("Index",data);
        }
       

        public IActionResult SearchProduct(string name)
        {
            var data = _productApi.ProductSearch(name);
            return View("Index", data);

        }
        public IActionResult SortByAsc(string price)
        {
            var data =_productApi.SortByAscending(price);
                return View("Index", data.Result);

        }
        public IActionResult SortByDescending(string price)
        {
            var data=_productApi.SortbyDescending(price);
            return View("Index", data.Result);

        }
    }
}

UILayer/Views/User/ForgotPassword.cshtml
@model DomainLayer.ForgotPassword
@{ 
    ViewData["Title"] = "ForgotPassword";
    Layout = "~/Views/User/WithoutNav.cshtml";
}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <div class="container" style="margin-top: 10%; margin-top: 100px;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 alert alert-info">
                @if (Model?.emailSent == true)
                {
                    <div class="alert alert-success" role="alert">
                        <p>We have sent an email to your registered email id</p>
                    </div>
                }
                else
                {
                    <div>
                        <h3 class="text-center">Forgot Password</h3>
                        <form id="ForgotPasswordForm" method="post" asp-action="ForgotPassword">
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                    <input class="form-control" type="text" asp-for="email" id="logEmail" placeholder="Email" />
                                    <span asp-validation-for="email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <input class="btn btn-info form-control" style="background-color: #0a8199" type="submit" value="Submit" />
                                </div>
                            </div>
                        </form>
                        <div class="col">
                            <a style="cursor:pointer; color:unset;" asp-action="Login">Back to Login</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

UILayer/Views/User/Index.cshtml
@model IEnumerable<DomainLayer.Product.ProductsModel>
@{
    ViewData["Title"] = "Index";
}


<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        max-width: 300px;
        margin: auto;
        text-align: center;
        font-family: arial;
        padding: 5%;
        width: 80%;
        height: 95%;
    }

    .price {
        color: grey;
        font-size: 22px;
    }

    .card button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 80%;
        font-size: 18px;
    }

    .card button:hover {
        opacity: 0.7;
    }

</style>

<h2 style="text-align:center">Products</h2>


    <div class="container">
        <div class="row">
            @foreach (var items in Model)
            {
                <div class="col-md-4">
                    <div class="card">
                        <a asp-route-id="@items.id" asp-controller="Product" asp-action="ProductDetails"><img src="~/images/ProductImages/@items.image" alt="Mobile" style="width: 45%; height: 90%; position: relative; left: 0px;"></a>

                        <h1 style="font-size: 145%;">@items.productName</h1>
                        <p class="price" style="color: black;">&#8377 @items.productPrice</p>
                        <p><a asp-route-id="@items.id" asp-controller="checkout" asp-action="BuyNow"><button class="btn btn-primary">Buy Now</button></a></p>
                        <p><button class="btn btn-primary">Add to Cart</button></p>
                    </div>
                </div>
            }
        </div>
    </div>

UILayer/Views/User/Login.cshtml
@model DomainLayer.Login
@{
    ViewData["Title"] = "Login";
}
@{
    @*var loginUrl = ViewData["LoginUrl"] as string;*@
    Layout = "~/Views/User/WithoutNav.cshtml";
    var error = TempData["error"] as string;
    Microsoft.Extensions.Primitives.StringValues queryVal = "";
    var returnUrl = ViewData["LoginUrl"] as string;
}


    @{
        <script type="text/javascript">
            function noBack() { window.history.forward() }
            noBack();
            window.onload = noBack;
            window.onpageshow = function (evt) { if (evt.persisted) noBack() }
            window.onunload = function () { void (0) }
        </script>
    }


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<div class="container" style="margin-top: 10%; margin-top:100px;">
    <div class="row">
        <div class="col-md-4 col-md-offset-4 alert alert-info">

            @if (Context.Request.Query.TryGetValue("ReturnUrl", out queryVal) && queryVal.FirstOrDefault() == "/admin")
            {
                <h3 class="text-center">Admin Login</h3>
            }
            else
            {
                <h3 class="text-center">Login</h3>
            }

            <form id="LoginForm" method="post" action="/user/login?ReturnUrl=@System.Net.WebUtility.UrlEncode(returnUrl)">

                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input class="form-control" type="email" asp-for="username" id="logEmail" placeholder="Email" />
                        <span asp-validation-for="username" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        <input class="form-control" type="password" asp-for="password" id="logPassword" placeholder="Password" />
                        <span asp-validation-for="password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-info form-control" style="background-color: #0a8199" type="submit"><i class="glyphicon glyphicon-log-in"></i> Login </button>
                </div>
            </form>
            @if (Context.Request.Query.TryGetValue("ReturnUrl", out queryVal) && queryVal.FirstOrDefault() == "/admin")
            {

            }
            else
            {
                <div class="form-group">
                    <a style="float:left" asp-action="ForgotPassword">Forgot Password?</a>
                    <a style="float:right;cursor:pointer;color:unset;" onclick="SignUp()" asp-action="UserRegister"> Sign Up </a>
                </div>
            }


        </div>
        <div class="form-group">
            @if (!string.IsNullOrEmpty(error))
            {
                <span class="alert-danger" style="padding: 20px; margin-left: 460px;">@error</span>
            }
        </div>
    </div>
</div>
<script>
    function SignUp() {

    }
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UILayer/Views/User/ResetPassword.cshtml
@model DomainLayer.ResetPassword
@{ 
    ViewData["Title"] = "ResetPassword";
    Layout = "~/Views/User/WithoutNav.cshtml";
}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <div class="container" style="margin-top: 10%; margin-top: 100px;">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 alert alert-info">
                <div>
                    <h3 class="text-center">Reset Password</h3>
                    <form id="ResetPasswordForm" method="post" action="/user/ResetPassword">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input class="form-control" type="password" asp-for="newPassword" id="logPassword" placeholder="New Password" />
                                <span asp-validation-for="newPassword" class="text-danger"></span>
                            </div>
                        </div>                      
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input class="form-control" type="password" asp-for="confirmPassword" id="logPassword" placeholder="Confirm Password" />
                                <span asp-validation-for="confirmPassword" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <input class="btn btn-info form-control" style="background-color: #0a8199" type="submit" value="Submit" />
                            </div>
                        </div>
                        <input asp-for="user.email" type="hidden" />
                    </form>
                    <div class="col">
                        <a style="cursor:pointer; color:unset;" asp-action="Login">Back to Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

UILayer/Views/User/WithoutNav.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UILayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*   <link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    <header>
        
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div>
        @RenderBody()
    </div>
    <partial name="Admin\_footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UILayer/Views/User/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UILayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
 @*   <link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="user" asp-action="Index">Mobizone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 col-12 row">
                        
                        <li class="nav-item col">
                            <form class="form-inline" asp-controller="user" asp-action="SearchProduct">
                                <input name="name" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" style="margin-left: 0px;padding-top: 5px; padding-bottom: 6px;" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" style="margin-left: 17px;padding-top: 5px; background-color:white" asp-controller="User" asp-action="account">@User.Identity.Name </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" style="margin-left: 0px;padding-top: 5px; padding-bottom: 6px;" asp-area="" asp-controller="User" asp-action="UserRegister">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-primary" style="margin-left: 17px;padding-top: 5px; padding-bottom: 6px;" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <partial name="Users\_UserSideBar" />
    <div>
        @RenderBody()
    </div>
    <partial name="Admin\_footer" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>