UILayer/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UILayer.ApiServices;

namespace UILayer.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly AdminApi _adminApi;
        public AdminController()
        {
            _adminApi = new AdminApi();
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("Login");
        }
        [Authorize]
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Userdata()
        {
            var _userlist = _adminApi.GetUserData();

            return View(_userlist);
        }
    }


}

UILayer/Controllers/MasterDataController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using DomainLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using UILayer.ApiServices;

namespace UILayer.Controllers
{
    public class MasterDataController : Controller
    {
        
        IConfiguration _configuration;
        private readonly INotyfService _notyf;
        private readonly Masterdataapi _masterdataapi;
        public MasterDataController(IConfiguration configuration, INotyfService notyf)
        {
            _configuration = configuration;
            _masterdataapi = new Masterdataapi(_configuration);
            _notyf = notyf;
        }
        /*[HttpGet]
        [Authorize]
        public IActionResult MasterData()
        {
            return View();
        }*/

        [HttpPost]
        public IActionResult Masterdata(MasterData master)
        {
            IEnumerable<MasterData> masterDatas = _masterdataapi.MasterDatas();
            bool data = _masterdataapi.MasterDataAdd(master);
            //if (masterDatas.Any(c => c.masterData.Equals(master.masterData)))
            //{
            //    _notyf.Error("Already exists");
            //}
            //else
            //{
            //    bool data = _masterdataapi.MasterDataAdd(master);
            //    if (data)
            //    {
            //        _notyf.Success(_configuration.GetSection("Master")["MasterAdded"].ToString());
            //    }
            //    else
            //    {
            //        _notyf.Error(_configuration.GetSection("Master")["MasterAddedError"].ToString());
            //    }

            //}
            ModelState.Clear();
            return View();

        }

        [HttpGet]
        [Authorize]
        public IActionResult MasterData(int id)
        {
            ViewBag.MasterTitle = (Master)id;
            var parentData = (Master)id;
            IEnumerable<MasterData> data = _masterdataapi.MasterDatas();
            var masterdata = data.Where(c => parentData.Equals(c.parentId));
            
            var count=masterdata.Count();
            return View(masterdata);

            //var datas= new MasterData();
            //var masterdata = _masterdataapi.MasterDatas();
            //var data = masterdata.Where(c => c.id.Equals(c.parentId));
            //return View(masterdata);
        }

        [HttpGet("MasterData/EditMaster/{id}")]
        public IActionResult MasterEdit(int id)
        {
            var datas = _masterdataapi.MasterDatas();
            var data = datas.Where(c => c.id.Equals(id)).FirstOrDefault();
            return View("EditMaster", data);
        }
        [HttpPost]
        public IActionResult EditMaster(MasterData data)
        {
            bool result = _masterdataapi.EditMasterData(data);
            return RedirectToAction("MasterDatalist", new { id = data.parentId });
        }
        //[HttpGet("MasterData/EditMaster/{id}")]
        //public IActionResult DeleteMaster(int id)
        //{
        //    var datas = _masterdataapi.MasterDatas();
        //    var data = datas.Where(c => c.id.Equals(id)).FirstOrDefault();
        //    return PartialView("EditMastr", data);
        //}
        //[HttpPost]
        //public IActionResult DeleteMaster(MasterData data)
        //{
        //    bool result = _masterdataapi.EditMasterData(data);
        //    return RedirectToAction("MasterDatalist", new { id = data.parentId });
        //}


    }
}

UILayer/Controllers/ProductController.cs
using DomainLayer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RepositoryLayer;
using RepositoryLayer.Interface;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using UILayer.Datas.Apiservices;
using UILayer.Controllers;
using DomainLayer.Product;
using Microsoft.Extensions.Configuration;
using UILayer.ApiServices;

namespace UILayer.Controllers
{
    public class ProductController : Controller
    {
        IConfiguration _configuration;
        ProductView Storage = null;
        private readonly ProductApi _productApi;
        private IWebHostEnvironment _webHostEnvironment;
        Masterdataapi _masterdataapi;

        public ProductController(IConfiguration configuration, IWebHostEnvironment hostEnvironment)
        {
            _configuration = configuration;
            _productApi = new ProductApi(_configuration);
            _webHostEnvironment = hostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        
        {
            var products = _productApi.GetProduct();
            return View(products);
        }

        [HttpGet]
        //public IActionResult GetList()

        //{
        //    var products = _productApi.GetProduct();
        //    return new JsonResult(products);
        //}

        [HttpGet]
        //public IActionResult ProductDetails(int id)

        //{
        //    var products = _productApi.GetProduct().Where(x => x.id.Equals(id)).FirstOrDefault();
        //    ViewData["Products"] = products;
        //    return View();
        //}

        public IActionResult Details(int id)
        {
            var products = _productApi.GetById(id);
            return View(products);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            Storage = new ProductView();
            ProductsModel product = _productApi.GetById(id);
            Storage.productName = product.productName;
            Storage.productPrice = product.productPrice;
            Storage.productModel = product.productModel;
            Storage.quantity = product.quantity;
            Storage.description = product.description;
            return View("Create", Storage);
        }

        public ActionResult Delete(int id)
        {
            bool result = _productApi.Delete(id);
            if (result)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductView product)
      {
            if (product.id == 0)
            {
                string stringFileName = UploadFile(product);
                var productsModel = new ProductsModel
                {
                    productName = product.productName,
                    productPrice = product.productPrice,
                    productModel = product.productModel,
                    image = stringFileName,
                    quantity = product.quantity,
                    description = product.description,
                    specification = product.specification                   
                };

                bool result = _productApi.Create(productsModel);
                if (result)
                {
                    return RedirectToAction("Index");                 
                }
              return Content("Failed");
            }
            else
            {
                string stringFileName = UploadFile(product);
                var productsModel = new ProductsModel
                {
                    id = product.id,
                    productName = product.productName,
                    productPrice = product.productPrice,
                    productModel = product.productModel,
                    image = stringFileName,
                    quantity = product.quantity,
                    description = product.description
                };
                bool result = _productApi.Edit(productsModel);
                if (result)
                {
                    return RedirectToAction("Index");
                }
                return Content("Failed");
            }
        }

        private string UploadFile(ProductView product)
        {
            string fileName = null;
            if (product.image != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "Images/ProductImages");
                fileName = Guid.NewGuid().ToString() + "-" + product.image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    product.image.CopyTo(fileStream);
                }
            }

            return fileName;
        }
        //public IActionResult SearchProduct(string name)
        //{
        //    var data = _productApi.ProductSearch(name);
        //    return View("Index", data);

        //}
        //[HttpPost("filter")]
        //public IActionResult filter(string brandName)
        //{

        //    var data = _productApi.GetProduct().Where(x => x.specification.productBrand.Equals(brandName));

           
        //    //IEnumerable<ProductView> filteredData = (IEnumerable<ProductView>)_productApi.GetProduct().Where(c => c.productStatus.Equals(Status.enable));
        //    //if (filteredData != null)
        //    //{
        //    //    if (brandName != null)
        //    //    {
        //    //        filteredData = (IEnumerable<ProductView>)_productApi.Filter(brandName).Result;
        //    //    }
        //    //    int count = 0;
        //    //    var productCount = filteredData.Count();
        //    //    int cout = 0;
        //    //    for (int i = 0; i <= 0; i++)
        //    //    {
        //    //        if (productCount > 10)
        //    //        {
        //    //            cout += 1;
        //    //        }
        //    //        productCount = productCount - 10;
        //    //    }
        //    //    var result = filteredData.Skip((int)count * 10).Take(10);
        //    //    ViewBag.count = cout;
        //    //    return View("Index", result);
        //    //}

        //    return View("Index");

        }

    }

UILayer/Controllers/SettingsController.cs
using DomainLayer.AdminSettings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UILayer.ApiServices;

namespace UILayer.Controllers
{
    public class SettingsController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly SettingsApi _settingsApi;
        public SettingsController(IConfiguration configuration)
        {
            _configuration = configuration;
            _settingsApi = new SettingsApi(_configuration);
        }

        [HttpGet]
        public IActionResult Contact()
        {
            var contactData = _settingsApi.GetContact().FirstOrDefault();
            return View(contactData);

        }

        [HttpGet]
        public IActionResult About()
        {

            var aboutData = _settingsApi.GetAbout().FirstOrDefault();
            return View(aboutData);
        }

        [HttpPost("CreateAbout")]
        private IActionResult CreateAbout(About about)
        {
            var createAbout = _settingsApi.CreateAbout(about);
            if (createAbout)
            {
                return View("About");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditAbout()
        {
             var aboutData = _settingsApi.GetAbout().FirstOrDefault();
            return View(aboutData);
        }

        [HttpPost]
        public IActionResult EditAbout(About about)
        {
            var createAbout = _settingsApi.EditAbout(about);
            if (createAbout)
            {
                return View("About", _settingsApi.GetAbout().FirstOrDefault());
            }
            return RedirectToAction("Index");
        }

        [HttpPost("CreateContact")]
        public  IActionResult CreateContact(Contact contact)
        {
            var createContact = _settingsApi.CreateContact(contact);
            if (createContact)
            {
                return View("Contact");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditContact()
        {
            var contactData = _settingsApi.GetContact().FirstOrDefault();
            return View(contactData);
        }

        [HttpPost]
        public IActionResult EditContact(Contact contact)
        {
            var editContact = _settingsApi.EditContact(contact);
            if (editContact)
            {
                return View("Contact");
            }
            return RedirectToAction("Index");
        }
    }
}

UILayer/Views/Shared/Admin/_AdminSidebar.cshtml
 <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
      <body>
      <div class="btns">
         <span class="fas fa-bars"></span>
      </div>
      <nav class="sidebar">
         <div class="text">
            Admin
         </div>
         <ul class="unorder">
            <li class="actives"><a href="#">Dashboard</a></li>
            <li>
               <a href="#" class="feat-btns">Product
               <span class="fas fa-caret-down first"></span>
               </a>
               <ul class="feat-show">
                  <li><a asp-action="Create" asp-controller="Product">Add Product</a></li>
                  <li><a href="#">Product List</a></li>
               </ul>
            </li>
            <li>
               <a href="#" class="serv-btns">Settings
               <span class="fas fa-caret-down second"></span>
               </a>
               <ul class="serv-show">
                  <li><a href="#">Contact us</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Privacy And Policy</a></li>
                <li><a asp-area="" asp-controller="MasterData" asp-action="MasterData">MasterData</a></li>
               </ul>
            </li>
            <li><a asp-area="" asp-controller="Admin" asp-action="Userdata">Users</a></li>
        <li><a asp-area="" asp-controller="" asp-action="">Orders</a></li>
 
         </ul>
      </nav>
     
      <script>
         $('.btns').click(function(){
           $(this).toggleClass("click");
           $('.sidebar').toggleClass("show");
         });
           $('.feat-btns').click(function(){
             $('nav ul .feat-show').toggleClass("show");
             $('nav ul .first').toggleClass("rotate");
           });
           $('.serv-btns').click(function(){
             $('nav ul .serv-show').toggleClass("show1");
             $('nav ul .second').toggleClass("rotate");
           });
           $('nav ul li').click(function(){
             $(this).addClass("active").siblings().removeClass("active");
           });
      </script>
   </body>
<style>
    *{
  margin: 0;
  padding: 0;
  user-select: none;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
    .btns {
        position: absolute;
        top: 15px;
        left: 45px;
        height: 45px;
        width: 45px;
        text-align: center;
        background: #1b1b1b;
        border-radius: 3px;
        cursor: pointer;
        transition: left 0.4s ease;
        margin-top: -10px;
        margin-left: -33px;
    }
.btns.click{
  left: 260px;
}
.btns span{
  color: white;
  font-size: 28px;
  line-height: 45px;
}
.btns.click span:before{
  content: '\f00d';
}
.sidebar{
  position: fixed;
  width: 250px;
  height: 500px;
  left: -250px;
  /*background: #1b1b1b;*/
  background:#c1c1c1;
  transition: left 0.4s ease;
}
.sidebar.show{
  left: 0px;
}
.sidebar .text{
  color: white;
  font-size: 25px;
  font-weight: 600;
  line-height: 65px;
  text-align: center;
  background: #1e1e1e;
  letter-spacing: 1px;
}
    .sidebar .unorder {
        background: #1b1b1b;
        height: 100%;
        width: 100%;
        list-style: none;
    }
nav ul li{
  line-height: 60px;
  border-top: 1px solid rgba(255,255,255,0.1);
}
nav ul li:last-child{
  border-bottom: 1px solid rgba(255,255,255,0.05);
}
nav ul li a{
  position: relative;
  color: white;
  text-decoration: none;
  font-size: 18px;
  padding-left: 40px;
  font-weight: 500;
  display: block;
  width: 100%;
  border-left: 3px solid transparent;
}
nav ul li.actives a{
  color: cyan;
  background: #1e1e1e;
  border-left-color: cyan;
}
nav ul li a:hover{
  background: #1e1e1e;
}
nav ul ul{
  position: static;
  display: none;
}
nav ul .feat-show.show{
  display: block;
}
nav ul .serv-show.show1{
  display: block;
}
nav ul ul li{
  line-height: 42px;
  border-top: none;
}
nav ul ul li a{
  font-size: 17px;
  color: #e6e6e6;
  padding-left: 80px;
}
nav ul li.actives ul li a{
  color: #e6e6e6;
  background: #1b1b1b;
  border-left-color: transparent;
}
nav ul ul li a:hover{
  color: cyan!important;
  background: #1e1e1e!important;
}
nav ul li a span{
  position: absolute;
  top: 50%;
  right: 20px;
  transform: translateY(-50%);
  font-size: 22px;
  transition: transform 0.4s;
}
nav ul li a span.rotate{
  transform: translateY(-50%) rotate(-180deg);
}
.content{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%,-50%);
  color: #202020;
  z-index: -1;
  text-align: center;
}
.content .header{
  font-size: 45px;
  font-weight: 600;
}
.content p{
  font-size: 30px;
  font-weight: 500;
}
</style>

UILayer/Views/Shared/Admin/_footer.cshtml
<style>
footer {
  display: flex;
  flex-direction: row;
  border-top: 1px solid;
  flex-wrap: wrap;
  margin-top:500px;
}
footer h5 a {
  display: flex;
  flex-direction: column;
}
footer h5 a img {
  width: 100px;
}
footer h5 a span {
  text-align: center;
}
footer > ul {
  margin: 0 auto;
  margin-top: 20px;
}
footer > ul > li ul {
  margin-left: 10px;
}
footer div {
  border-top: 1px solid;
  flex: 0 0 100%;
  margin-top: 10px;
}
footer div p {
  text-align: center;
  padding: 10px;
}
 a{
    text-decoration:none;
}
li{
     list-style:none;
}
.about{
    margin-top:10px;
}
.privacy{
    margin-top:10px;
}
.contact{
    margin-top:10px;
}
                </style>
                 <footer>
            <h5>
                <a href="#"><img src="~/Images/MobiZone-logos_black.png" /> <span>MobiZone</span> </a>
            </h5>

            <ul>

                <li>
                    <a href="#">Company</a>
                    <ul>
                        <li class="about"><a asp-controller="Settings" asp-action="About">About</a></li>
                        <li class="privacy"><a asp-controller="Settings" asp-action="About">Privacy & Policy</a></li>
                        <li class="contact"><a asp-controller="Settings" asp-action="Contact">Contact Us</a></li>
                    </ul>
                </li>

            </ul>

            <div>
                <p><i class="fa fa-copyright" aria-hidden="true"></i> Mobizone Pivate limited</p>
            </div>

        </footer>